-- MySQL Script generated by MySQL Workbench
-- Thu Feb  2 04:19:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema university
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema university
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `university` DEFAULT CHARACTER SET utf8mb4 ;
USE `university` ;

-- -----------------------------------------------------
-- Table `university`.`colleges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`colleges` (
  `college_number` BIGINT(20) UNSIGNED NOT NULL,
  `college_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`college_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `university`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`courses` (
  `course_number` BIGINT(20) UNSIGNED NOT NULL,
  `course_name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `credit_hours` INT(10) UNSIGNED NOT NULL,
  `level` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`course_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `university`.`sections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`sections` (
  `section_number` BIGINT(20) UNSIGNED NOT NULL,
  `instructor_name` VARCHAR(255) NOT NULL,
  `semester` VARCHAR(255) NOT NULL,
  `year` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`section_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `university`.`course_sections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`course_sections` (
  `section_number` BIGINT(20) UNSIGNED NOT NULL,
  `course_number` BIGINT(20) UNSIGNED NOT NULL,
  INDEX `course_sections_section_number_foreign` (`section_number` ASC) VISIBLE,
  INDEX `course_sections_course_number_foreign` (`course_number` ASC) VISIBLE,
  CONSTRAINT `course_sections_course_number_foreign`
    FOREIGN KEY (`course_number`)
    REFERENCES `university`.`courses` (`course_number`),
  CONSTRAINT `course_sections_section_number_foreign`
    FOREIGN KEY (`section_number`)
    REFERENCES `university`.`sections` (`section_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `university`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`departments` (
  `code` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `college_number` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`code`),
  INDEX `departments_college_number_foreign` (`college_number` ASC) VISIBLE,
  CONSTRAINT `departments_college_number_foreign`
    FOREIGN KEY (`college_number`)
    REFERENCES `university`.`colleges` (`college_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `university`.`department_courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`department_courses` (
  `department_code` VARCHAR(255) NOT NULL,
  `course_number` BIGINT(20) UNSIGNED NOT NULL,
  INDEX `department_courses_department_code_foreign` (`department_code` ASC) VISIBLE,
  INDEX `department_courses_course_number_foreign` (`course_number` ASC) VISIBLE,
  CONSTRAINT `department_courses_course_number_foreign`
    FOREIGN KEY (`course_number`)
    REFERENCES `university`.`courses` (`course_number`),
  CONSTRAINT `department_courses_department_code_foreign`
    FOREIGN KEY (`department_code`)
    REFERENCES `university`.`departments` (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `university`.`department_phones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`department_phones` (
  `department_code` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  INDEX `department_phones_department_code_foreign` (`department_code` ASC) VISIBLE,
  CONSTRAINT `department_phones_department_code_foreign`
    FOREIGN KEY (`department_code`)
    REFERENCES `university`.`departments` (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `university`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`students` (
  `national_id` BIGINT(20) UNSIGNED NOT NULL,
  `student_number` BIGINT(20) UNSIGNED NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `middle_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `apartment_number` VARCHAR(255) NOT NULL,
  `street_number` VARCHAR(255) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `state` VARCHAR(255) NOT NULL,
  `postal_code` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `birthdate` DATE NOT NULL,
  `gender` ENUM('M', 'F') NOT NULL,
  `level` INT(11) NOT NULL,
  `major_department_code` VARCHAR(255) NOT NULL,
  `minor_department_code` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`student_number`),
  UNIQUE INDEX `students_national_id_student_number_unique` (`national_id` ASC, `student_number` ASC) VISIBLE,
  INDEX `students_major_department_code_foreign` (`major_department_code` ASC) VISIBLE,
  INDEX `students_minor_department_code_foreign` (`minor_department_code` ASC) VISIBLE,
  CONSTRAINT `students_major_department_code_foreign`
    FOREIGN KEY (`major_department_code`)
    REFERENCES `university`.`departments` (`code`),
  CONSTRAINT `students_minor_department_code_foreign`
    FOREIGN KEY (`minor_department_code`)
    REFERENCES `university`.`departments` (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `university`.`student_courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`student_courses` (
  `student_number` BIGINT(20) UNSIGNED NOT NULL,
  `course_number` BIGINT(20) UNSIGNED NOT NULL,
  INDEX `student_courses_student_number_foreign` (`student_number` ASC) VISIBLE,
  INDEX `student_courses_course_number_foreign` (`course_number` ASC) VISIBLE,
  CONSTRAINT `student_courses_course_number_foreign`
    FOREIGN KEY (`course_number`)
    REFERENCES `university`.`courses` (`course_number`),
  CONSTRAINT `student_courses_student_number_foreign`
    FOREIGN KEY (`student_number`)
    REFERENCES `university`.`students` (`student_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `university`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`teachers` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `salary` DECIMAL(8,2) UNSIGNED NOT NULL,
  `department_code` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `teachers_department_code_foreign` (`department_code` ASC) VISIBLE,
  CONSTRAINT `teachers_department_code_foreign`
    FOREIGN KEY (`department_code`)
    REFERENCES `university`.`departments` (`code`))
ENGINE = InnoDB
AUTO_INCREMENT = 76
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `university`.`teacher_courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`teacher_courses` (
  `teacher_id` BIGINT(20) UNSIGNED NOT NULL,
  `course_number` BIGINT(20) UNSIGNED NOT NULL,
  INDEX `teacher_courses_teacher_id_foreign` (`teacher_id` ASC) VISIBLE,
  INDEX `teacher_courses_course_number_foreign` (`course_number` ASC) VISIBLE,
  CONSTRAINT `teacher_courses_course_number_foreign`
    FOREIGN KEY (`course_number`)
    REFERENCES `university`.`courses` (`course_number`),
  CONSTRAINT `teacher_courses_teacher_id_foreign`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `university`.`teachers` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
